services:
  - type: web
    name: chat-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p logs
      chmod -R 777 logs
    startCommand: gunicorn --workers 2 --timeout 120 --access-logfile - --error-logfile - 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_TO_STDOUT
        value: "true"
    disk:
      name: app-logs
      mountPath: /opt/render/project/src/logs
      sizeGB: 1