chatbots:
  chatbot_PDN:
    name: "PDN"
    title: "המאמן שלך למציאת הצופן שלך בשיטת PDN"
    description: "אני כאן כדי לעזור לך למציאת הצופן שלך."
    welcome_message: |
      שלום! אני PDN – המדריך האישי שלך לגילוי הצופן הייחודי שטמון בך.  
      יחד נצא למסע מרתק שבו נגלה 💡 את הכוחות שמניעים אותך.   
      את סגנון הפעולה שלך.   
      ואת הקוד 🧬 שיגלה מי אתה באמת.   
      מוכן/ה להתחיל? 
    contact_email: "tomergur@gmail.com"
    version: "1.0.0"
